#!/bin/sh

# wrap-for-bin.sh: Template for git executable wrapper scripts
# to run test suite against sandbox, but with only bindir-installed
# executables in PATH.  The Makefile copies this into various
# files in bin-wrappers, substituting
# /artifact/git and git.

GIT_EXEC_PATH='/artifact/git'
if test -n "$NO_SET_GIT_TEMPLATE_DIR"
then
        unset GIT_TEMPLATE_DIR
else
        GIT_TEMPLATE_DIR='/artifact/git/templates/blt'
        export GIT_TEMPLATE_DIR
fi
GITPERLLIB='/artifact/git/perl/build/lib'"${GITPERLLIB:+:$GITPERLLIB}"
GIT_TEXTDOMAINDIR='/artifact/git/po/build/locale'
PATH='/artifact/git/bin-wrappers:'"$PATH"

export GIT_EXEC_PATH GITPERLLIB PATH GIT_TEXTDOMAINDIR

LD_PRELOAD=/artifact/tools/binary-instrumentation/build/libcollect-trace-preload.so
export LD_PRELOAD

CON_TRACE_SOURCE=1
export CON_TRACE_SOURCE

case "$GIT_DEBUGGER" in
'')
        exec "${GIT_EXEC_PATH}/git" "$@"
        ;;
1)
        unset GIT_DEBUGGER
        exec gdb --args "${GIT_EXEC_PATH}/git" "$@"
        ;;
*)
        GIT_DEBUGGER_ARGS="$GIT_DEBUGGER"
        unset GIT_DEBUGGER
        exec ${GIT_DEBUGGER_ARGS} "${GIT_EXEC_PATH}/git" "$@"
        ;;
esac
